# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYTimes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYTimes

  target 'NYTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTimesUITests' do
    inherit! :search_paths
    # Pods for testing
  end


  pod 'SwiftLint', :inhibit_warnings => true
  pod 'Alamofire'

end
